### ISSUE TITLE
Item display name showing up as "item.modname.itemname" instead of using the en-us.json translation key

### ISSUE THREAD

**Issue by Lynden-Sylvester** [Tutorials-By-Kaupenjoe/Minecraft-1.16.5#7]
I followed episode 3 of your modded 1.16.5 tutorial series, but I can't figure out why the en-us.json is reading the translation key identifier, but not the actual associated translation.

Ie.

If I was doing an amethyst, it's reading as:

"item.tutorialmod.amethyst" in-game instead of:

"Amethyst".

the en-us.json is not being read correctly.

I'm doing this in 1.16.5
<img width="445" alt="Screen Shot 2022-07-02 at 2 34 25 AM" src="https://user-images.githubusercontent.com/78802283/176989614-ae8b9978-9fb1-4c39-9ec6-2402dd0b51fc.png">

**Comment by goodstealing** [comment]
OU Shit, I ran into the same problem, they have not yet been solved _ (
